version: '3'
services:
  db:
    image: mysql:latest
    restart: unless-stopped
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=devrootpassword
      - MYSQL_DATABASE=dev_mycareer
      - MYSQL_USER=devuser
      - MYSQL_PASSWORD=devpassword

  app:
    container_name: web_app
    build: .
    restart: on-failure
    ports:
      - '3001:3001'
    depends_on:
      - db
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development
      - DATABASE_URL=mysql://root:devrootpassword@db/dev_mycareer
    tty: true
    stdin_open: true
